openapi: 3.0.0
info:
  title: Trail Day API
  description: API documentation for the Trail Day REST API
  version: 1.0.0

servers:
  - url: http://localhost:8080

paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: OK

  /api/v1/auth/login:
    post:
      summary: User login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Successful login